from acc import out, SAME
S = {
 "fr_lotv": ("https://www.fragrantica.com/notes/Lily-of-the-Valley-109.html", "Lily-of-the-Valley perfume ingredient, Lily-of-the-Valley fragrance and essential oils"),
 "pf_muguet": ("https://img.perfumerflavorist.com/files/base/allured/all/document/2016/04/pf.8041.pdf", "Muguet in Perfumery"),
 "ps_guerlainmuguet": ("https://perfumesociety.org/guerlain-muguet-2021-legendary-lily-of-the-valley/", "Guerlain Muguet 2021 – legendary lily of the valley - The Perfume Society"),
 "ps_lucky": ("https://perfumesociety.org/little-lucky-charms-six-lovely-lily-valley-scents-spritz-may-day/", "Little lucky charms - Six lovely Lily of the Valley scents to spritz this May Day - The Perfume Society"),
 "fr_mag": ("https://www.fragrantica.com/notes/Magnolia-147.html", "Magnolia perfume ingredient, Magnolia fragrance and essential oils Magnolia grandiflora (Magnoliaceae)"),
 "ps_mag": ("https://perfumesociety.org/ingredients-post/magnolia/", "Magnolia - The Perfume Society"),
 "ps_magmyth": ("https://perfumesociety.org/magnolia-history-scented-myths-the-science-of-lust/", "Magnolia: History, Scented Myths & the Science of Lust - The Perfume Society"),
 "fr_mari": ("https://www.fragrantica.com/notes/Marigold-153.html", "Marigold perfume ingredient, Marigold fragrance and essential oils Tagetes lemmonii (Asteraceae)"),
 "sc_tagetes": ("https://www.scentspiracy.com/fragrance-ingredients/p/tagete-oil", "Tagetes Oil (8016-84-0) – High-Impact Green-Fruity Natural Ingredient for Perfumery — Scentspiracy"),
 "fw_tagetes": ("https://fraterworks.com/products/tagetes-oil", "Tagetes Oil – Fraterworks"),
 "ps_mari": ("https://perfumesociety.org/ingredients-post/marigold/", "Marigold - The Perfume Society"),
 "wp_tagetes": ("https://en.wikipedia.org/wiki/Tagetes", "Tagetes - Wikipedia"),
 "at_spinal": ("https://ataraxiaperfumery.com/products/spinal-fluid", "Spinal Fluid", "Ataraxia Perfumery"),
 "fr_mim": ("https://www.fragrantica.com/notes/Mimosa-167.html", "Mimosa perfume ingredient, Mimosa fragrance and essential oils Acacia Decurrens Var. Dealbata (Mimosaceae)"),
 "fr_mimcolor": ("https://www.fragrantica.com/news/Color-and-Smell-Part-I-Mimosa-9210.html", "Color & Smell, Part I: Mimosa ~ Raw Materials ~ Fragrantica"),
 "ps_mim": ("https://perfumesociety.org/ingredients-post/mimosa/", "Mimosa - The Perfume Society"),
 "fr_wild": ("https://www.fragrantica.com/notes/Wildflowers-379.html", "Wildflowers perfume ingredient, Wildflowers fragrance and essential oils"),
 "pw_list": ("https://pinewardperfume.com/pages/master-scent-list", "Master Scent List", "Pineward"),
 "fr_meadowmoss": ("https://www.fragrantica.com/perfume/Pineward-Perfumes/Meadowmoss-83378.html", "Meadowmoss Pineward Perfumes perfume - a fragrance for women and men 2023"),
 "fr_nectar": ("https://www.fragrantica.com/notes/Nectar-1694.html", "Nectar perfume ingredient, Nectar fragrance and essential oils"),
 "fr_honey": ("https://www.fragrantica.com/notes/Honey-181.html", "Honey perfume ingredient, Honey fragrance and essential oils"),
 "at_deity": ("https://ataraxiaperfumery.com/products/deity", "Deity", "Ataraxia Perfumery"),
 "wp_neroli": ("https://en.wikipedia.org/wiki/Neroli", "Neroli - Wikipedia"),
 "fr_nerob": ("https://www.fragrantica.com/news/Neroli-vs-Orange-Blossom-in-Perfumery-15054.html", "Neroli vs Orange Blossom in Perfumery ~ Raw Materials ~ Fragrantica"),
 "fr_obn": ("https://www.fragrantica.com/news/Orange-Blossom-Neroli-2974.html", "Orange Blossom & Neroli ~ Raw Materials ~ Fragrantica"),
 "ps_ob": ("https://perfumesociety.org/ingredients-post/orange-blossom/", "Orange blossom - The Perfume Society"),
 "fr_ob": ("https://www.fragrantica.com/notes/Orange-Blossom-16.html", "Orange Blossom perfume ingredient, Orange Blossom fragrance and essential oils Citrus aurantium"),
 "wp_orris": ("https://en.wikipedia.org/wiki/Orris_root", "Orris root - Wikipedia"),
 "ps_orris": ("https://perfumesociety.org/ingredients-post/orris-root/", "Orris root - The Perfume Society"),
 "fr_orris": ("https://www.fragrantica.com/notes/Orris-Root-101.html", "Orris Root perfume ingredient, Orris Root fragrance and essential oils Iris germanica, Iris florentina, Iris pallida"),
 "fw_irisprimer": ("https://fraterworks.com/blogs/information/iris-naturals-a-primer", "Iris Naturals, A Primer – Fraterworks"),
 "ps_iris": ("https://perfumesociety.org/ingredients-post/iris/", "Iris - The Perfume Society"),
 "fw_pallidabutter": ("https://fraterworks.com/products/orris-pallida-butter-aged", "Orris Pallida Butter – Fraterworks"),
 "st_irispallida": ("https://www.scentree.co/en/Iris_pallida_absolute.html", "ScenTree - Iris pallida absolute (CAS N° 8002-73-1)"),
 "la_douleur": ("https://lesabstraits.com/products/la-douleur-exquise", "La Douleur Exquise", "Les Abstraits"),
 "fr_osm": ("https://www.fragrantica.com/notes/Osmanthus-10.html", "Osmanthus perfume ingredient, Osmanthus fragrance and essential oils"),
 "fw_osm": ("https://fraterworks.com/products/osmanthus-gold-absolute", "Osmanthus “Gold” Absolute – Fraterworks"),
 "ps_osm": ("https://perfumesociety.org/osmanthus-the-charming-blossom-that-wraps-the-senses/", "Osmanthus: The Charming Blossom That Wraps the Senses - The Perfume Society"),
 "fr_osmnews": ("https://www.fragrantica.com/news/Perfume-Note-Osmanthus-Blossom-3508.html", "Perfume Note - Osmanthus Blossom ~ Raw Materials ~ Fragrantica"),
 "adar_amber": ("https://adarperfumes.com/products/amber-zero-essence-of-dephts", "Amber Zero: Essence of Depths", "ADAR Perfumes"),
 "fr_passflower": ("https://www.fragrantica.com/notes/Passion-Flower-162.html", "Passion Flower perfume ingredient, Passion Flower fragrance and essential oils Passiflora (Passifloraceae)"),
 "wp_passiflora": ("https://en.wikipedia.org/wiki/Passiflora", "Passiflora - Wikipedia"),
 "fr_plumblossom": ("https://www.fragrantica.com/notes/Plum-Blossom-385.html", "Plum Blossom perfume ingredient, Plum Blossom fragrance and essential oils Prunus mume"),
 "fr_plumnews": ("https://www.fragrantica.com/news/Plum-23276.html", "Plum ~ Columns ~ Fragrantica"),
 "wp_mume": ("https://en.wikipedia.org/wiki/Prunus_mume", "Prunus mume - Wikipedia"),
 "fr_pollen": ("https://www.fragrantica.com/notes/Pollen-896.html", "Pollen perfume ingredient, Pollen fragrance and essential oils"),
 "fr_bee": ("https://www.fragrantica.com/perfume/Zoologist-Perfumes/Bee-58140.html", "Bee Zoologist Perfumes perfume - a fragrance for women and men 2019"),
 "at_vestibule": ("https://ataraxiaperfumery.com/products/vestibule", "Vestibule", "Ataraxia Perfumery"),
 "fr_rose": ("https://www.fragrantica.com/notes/Rose-105.html", "Rose perfume ingredient, Rose fragrance and essential oils Rosa gallica, centifollia, damascena"),
 "ps_rose": ("https://perfumesociety.org/ingredients-post/rose/", "Rose - The Perfume Society"),
 "wp_roseoil": ("https://en.wikipedia.org/wiki/Rose_oil", "Rose oil - Wikipedia"),
 "fr_howmany": ("https://www.fragrantica.com/news/How-Many-Roses-6503.html", "How Many Roses? ~ Columns ~ Fragrantica"),
 "fr_whiterose": ("https://www.fragrantica.com/board/viewtopic.php?id=352487", "The scent of white roses? (Page 1) — General Perfume Talk — Fragrantica Club", "Fragrantica Club"),
 "wp_absolute": ("https://en.wikipedia.org/wiki/Absolute_(perfumery)", "Absolute (perfumery) - Wikipedia"),
 "wp_centifolia": ("https://en.wikipedia.org/wiki/Rosa_%C3%97_centifolia", "Rosa × centifolia - Wikipedia"),
 "fw_rosedemai": ("https://fraterworks.com/products/rose-de-mai-absolute", "Rose de Mai Absolute, France – Fraterworks"),
 "fr_grasserose": ("https://www.fragrantica.com/news/Grasse-The-Way-of-the-Rose-13688.html", "Grasse: The Way of the Rose ~ Raw Materials ~ Fragrantica"),
 "pm_moroccan": ("https://www.parfumo.com/Fragrance_Note/Moroccan_Rosa_centifolia", "Moroccan Rosa centifolia", "Parfumo"),
 "th_taif": ("https://thursd.com/articles/saudi-arabia-taif-damask-rose", "Saudi Arabia's Taif Damask Rose", "Thursd"),
 "ith_taif": ("https://ithra.com/en/news/taif-city-roses", "Add to Your Bucket List: Fragrant Taif", "Ithra"),
 "pp_taif": ("https://premierepeau.com/pages/glossary-terms/taif-rose", "Taif Rose", "Premiere Peau"),
 "bn_rose": ("https://basenotes.com/threads/rose.231422/", "Rose", "Basenotes"),
 "tg_turkrose": ("https://thegoodscentscompany.com/data/ab1591211.html", "rose absolute (rosa damascena) turkey", "The Good Scents Company"),
 "rhs_snowdrop": ("https://www.rhs.org.uk/plants/536629/galanthus-siskin-d/details", "Galanthus 'Siskin' (d)", "Royal Horticultural Society"),
 "arun_snowdrop": ("https://www.aruncountryside.org/blog/the-serenity-of-snowdrops", "The Serenity of Snowdrops", "Arun Countryside Trust"),
 "fr_tiare": ("https://www.fragrantica.com/notes/Tiare-Flower-148.html", "Tiare Flower perfume ingredient, Tiare Flower fragrance and essential oils Gardenia tahitensis (Rubiaceae)"),
 "wp_tiare": ("https://en.wikipedia.org/wiki/Gardenia_taitensis", "Gardenia taitensis - Wikipedia"),
 "ps_tiare": ("https://perfumesociety.org/ingredients-post/tiare/", "Tiaré - The Perfume Society"),
 "wp_monoi": ("https://en.wikipedia.org/wiki/Mono%C3%AF_oil", "Monoï oil - Wikipedia"),
 "fr_tobblossom": ("https://www.fragrantica.com/notes/Tobacco-Blossom-346.html", "Tobacco Blossom perfume ingredient, Tobacco Blossom fragrance and essential oils Nicotiana Alata"),
 "fr_whitetob": ("https://www.fragrantica.com/notes/White-Tobacco-345.html", "White Tobacco perfume ingredient, White Tobacco fragrance and essential oils Nicotiana Suaveolens"),
 "tg_tobflower": ("https://www.thegoodscentscompany.com/data/ab1067371.html", "tobacco flower absolute, 8037-19-2", "The Good Scents Company"),
 "fr_tube": ("https://www.fragrantica.com/notes/Tuberose-25.html", "Tuberose perfume ingredient, Tuberose fragrance and essential oils Polianthes tuberosa"),
 "ps_tube": ("https://perfumesociety.org/ingredients-post/tuberose/", "Tuberose - The Perfume Society"),
 "fr_tubenews": ("https://www.fragrantica.com/news/Tuberose-Flower-Scent-History-and-Perfume-5041.html", "Tuberose: Flower, Scent, History and Perfume ~ Interviews ~ Fragrantica"),
 "fr_violet": ("https://www.fragrantica.com/notes/Violet-116.html", "Violet perfume ingredient, Violet fragrance and essential oils Viola odorata"),
 "ps_violet": ("https://perfumesociety.org/ingredients-post/violet/", "Violet - The Perfume Society"),
 "ps_ionone": ("https://perfumesociety.org/ingredients-post/ionone/", "Ionone - The Perfume Society"),
 "fr_waterlily": ("https://www.fragrantica.com/notes/Water-Lily-30.html", "Water Lily perfume ingredient, Water Lily fragrance and essential oils"),
 "ps_waterlily": ("https://perfumesociety.org/ingredients-post/water-lily/", "Water lily - The Perfume Society"),
 "ps_aquatic": ("https://perfumesociety.org/dive-into-aquatic-fragrances/", "Dive Into Aquatic Fragrances - The Perfume Society"),
 "fr_lotus": ("https://www.fragrantica.com/notes/Lotus-27.html", "Lotus perfume ingredient, Lotus fragrance and essential oils Nelumbo nucifera"),
 "tg_whitelotus": ("https://www.thegoodscentscompany.com/data/ab1592161.html", "white nelumbo nucifera flower absolute", "The Good Scents Company"),
 "fw_pinklotus": ("https://fraterworks.com/products/pink-lotus-absolute", "Pink Lotus Absolute – Fraterworks"),
 "fr_yellow": ("https://www.fragrantica.com/notes/Yellow-Flowers-1309.html", "Yellow Flowers perfume ingredient, Yellow Flowers fragrance and essential oils"),
 "fr_yellowcascade": ("https://www.fragrantica.com/news/A-Cascade-of-Yellow-Florals-Translating-the-Color-Signal-into-Olfactory-Constituents-4698.html", "A Cascade of Yellow Florals: Translating the Color Signal into Olfactory Constituents ~ Raw Materials ~ Fragrantica"),
 "fr_brighter": ("https://www.fragrantica.com/news/Brighter-Than-Sunshine-5-Niche-Fragrances-With-White-and-Yellow-Flowers-20382.html", "Brighter Than Sunshine: 5 Niche Fragrances With White and Yellow Flowers ~ Fragrance Reviews ~ Fragrantica"),
 "fr_ylang": ("https://www.fragrantica.com/notes/Ylang-Ylang-24.html", "Ylang-Ylang perfume ingredient, Ylang-Ylang fragrance and essential oils"),
 "ps_ylang": ("https://perfumesociety.org/ingredients-post/ylang-ylang/", "Ylang ylang - The Perfume Society"),
 "wp_cananga": ("https://en.wikipedia.org/wiki/Cananga_odorata", "Cananga odorata - Wikipedia"),
 "fw_ylang": ("https://fraterworks.com/collections/ylang-ylang-collection", "Ylang-Ylang Collection – Fraterworks"),
}
N = {
 "note-lily-of-the-valley": dict(
  say="The tiny white bells of May, lucky charms in France. Their smell is fresh, green and dewy, clean and delicate: cool morning air, snapped green stems, a wet garden on a warm spring morning, with a faint sweetness. The flower is too fragile to give any oil at all, so every lily of the valley in a perfume is built by the perfumer from molecules, one of the great tricks of the trade.",
  src=["fr_lotv", "pf_muguet", "ps_guerlainmuguet", "ps_lucky"],
  vars={"Lily-of-the-Valley": dict(same=SAME)}),
 "note-magnolia": dict(
  say="The big, creamy flowers of the magnolia tree. They smell softly floral and creamy-sweet, a little like jasmine but lighter, with a bright, fresh lemony edge, a hint of honey and sometimes something faintly salty. There are some two hundred kinds of magnolia and they smell different, some of lemon, some of vanilla, some of violet or spice.",
  src=["fr_mag", "ps_mag", "ps_magmyth"]),
 "note-marigold": dict(
  say="Tagetes, the pungent orange marigold, and a far stranger smell than its cheerful colour suggests: a burst of crushed green leaves and bitter herbs, sharp and vegetal, then a sweet, fruity side like green apple and apricot, a little like chamomile. It is powerful and restricted, used in traces to brighten flowers and fruits and make them feel wild.",
  src=["fr_mari", "sc_tagetes", "fw_tagetes", "ps_mari"],
  vars={
   "Marigold EO": dict(say="EO stands for essential oil: marigold here is the real steam-distilled oil of tagetes, not a marigold accord built from other materials, so it has the plant's full pungent green, fruity strangeness.", src=["at_spinal", "fw_tagetes", "wp_tagetes"]),
  }),
 "note-mimosa": dict(
  say="The fluffy yellow pompom flowers of the silver wattle, a sign of the end of winter in the south of France. The absolute smells yellow and sunny: warm, honeyed and powdery, a little like iris and almond, with a fresh, green, almost cucumber-like facet. It is so strong that perfumers rarely use more than a trace.",
  src=["fr_mim", "fr_mimcolor", "ps_mim"]),
 "note-mountain-wildflowers": dict(
  say="No single flower: the smell of a high meadow in bloom, a fantasy note of many small wild flowers together. It is sweet and aromatic, softly floral, with a green and herbal edge from the grass and leaves around them, and the clean air of altitude. It is Pineward painting a landscape rather than naming a material.",
  src=["fr_wild", "pw_list", "fr_meadowmoss"]),
 "note-nectar": dict(
  say="The sugary liquid flowers make to draw in bees, imagined as a smell: sweet, thick and a little sticky, like runny honey or syrup, with a jammy richness and a floral softness around it. It is an impression rather than a material, and it makes the flowers near it feel warm and edible.",
  src=["fr_nectar", "fr_honey", "at_deity"]),
 "note-neroli": dict(
  say="The white blossom of the bitter orange, distilled with steam. It is fresh, green and a little bitter, citrusy and honeyed at once, clean and faintly soapy, with a touch of something metallic. It is lighter and greener than orange blossom absolute, which comes from the same flower, and it is a pillar of eau de cologne.",
  src=["wp_neroli", "fr_nerob", "fr_obn"],
  vars={"Neroli Blossom": dict(same="No change: neroli is already the oil of the bitter orange's blossom.")}),
 "note-orange-blossom": dict(
  say="The same white blossom as neroli, but taken with solvents rather than steam, so it smells richer, sweeter, warmer and headier: honeyed and heady, with a jasmine-like, slightly animal depth. Where neroli is fresh and green, orange blossom is sensual and full, and together they smell most like the flowers on the tree.",
  src=["ps_ob", "fr_ob", "fr_nerob"]),
 "note-orris": dict(
  say="The root of the iris, not its flower: dug up, dried and stored for three years or more while its scent slowly develops, then ground and distilled. The result is one of the costliest materials in perfumery, and one of the most beautiful: soft, powdery and cool, like violets, suede and face powder, with an earthy, woody, buttery depth. It gives a perfume elegance and hush, and it helps it last.",
  src=["wp_orris", "ps_orris", "fr_orris", "fw_irisprimer"],
  vars={
   "Orris Root": dict(same="No change: orris is the root of the iris already."),
   "Iris": dict(say="In perfume 'iris' almost always means orris, the dried root: the flower itself gives next to nothing. So it names the plant rather than a different material: the same soft, powdery, violet-and-suede smell.", src=["ps_iris", "wp_orris"]),
   "Iris Butter": dict(say="Orris in its most classic form: the dried, powdered root is distilled, and the oil sets into a pale, waxy solid, the butter. It is the most natural and complete orris, creamy and powdery, and its worth is counted by how much irone, the violet-like molecule, it holds.", src=["fw_pallidabutter", "wp_orris", "fw_irisprimer"]),
   "Iris Pallida": dict(say="The pale iris of Tuscany, the most sought-after species for orris. Its root gives the finest, most violet-like and powdery orris, and its absolute is among the most expensive materials a perfumer can buy.", src=["wp_orris", "st_irispallida", "la_douleur"]),
  }),
 "note-osmanthus": dict(
  say="A tiny apricot-coloured flower from China, where it scents tea. Its absolute is fruity and leathery at once: ripe apricot and peach skin, honeyed petals and a suggestion of suede, with a tea-like softness and a violet sweetness. It is warm and golden, and quietly unusual.",
  src=["fr_osm", "fw_osm", "ps_osm", "fr_osmnews"],
  vars={
   "Leathery Osmanthus": dict(say="Not a different flower but osmanthus as ADAR presents it, with its leather side put forward: the suede that is always there under the apricot, turned up so the flower feels darker and drier.", src=["adar_amber", "fr_osm", "fw_osm"]),
  }),
 "note-passionflower": dict(
  say="The extraordinary purple flower of the passion-fruit vine. Its smell is delicate, sweet and fruity, tropical and a little like grapes, with a green, dewy freshness of cut stems. No oil is taken from it, so in perfume it is an imagined, juicy floral.",
  src=["fr_passflower", "wp_passiflora"],
  vars={"Passion Flower": dict(same=SAME)}),
 "note-plum-blossom": dict(
  say="The pale blossom of the Asian plum, ume, which flowers in late winter and announces spring in Japan and China. It is a soft, musky floral with a light sweetness and a faint fruitiness in the background, powdery and delicate rather than juicy.",
  src=["fr_plumblossom", "fr_plumnews", "wp_mume"]),
 "note-pollen": dict(
  say="The golden dust at the heart of a flower, imagined as a smell: sweet, powdery and honey-like, soft and a little dusty, sometimes slightly bitter. It gives flowers a fuzzy, realistic texture, and it belongs with honey and beeswax in the smell of a hive.",
  src=["fr_pollen", "fr_bee", "at_vestibule"]),
 "note-rose": dict(
  say="The queen of perfumery and, with jasmine, one of its two pillars. Rose is a whole world: fresh petals at dawn, cool and dewy and a little lemony, or a heavy bouquet in a warm room, honeyed, jammy and spicy. It is taken two ways, distilled into rose otto or extracted into rose absolute, mostly from the damask rose and the hundred-petalled centifolia, and it takes thousands of flowers to make a little.",
  src=["fr_rose", "ps_rose", "wp_roseoil", "fr_howmany"],
  vars={
   "Red Rose": dict(say="Not a different material but the rose as it is imagined in red: richer, deeper and velvety, a little peppery, where a white rose reads light and fresh. The colour of a real rose does not decide its smell, so this is a mood the perfumer builds.", src=["fr_rose", "fr_whiterose"]),
   "White Rose": dict(say="The rose imagined in white: lighter, fresher and more delicate, dewy and a little citrus, where a red rose is richer and more velvety. It is a mood the perfumer builds rather than a different oil, since a rose's colour does not decide its smell.", src=["fr_whiterose", "fr_rose"]),
   "Rose Absolute": dict(say="Rose taken with solvents rather than steam. The absolute keeps more of the living flower: deeper, honeyed and longer-lasting than rose otto, the distilled oil, which is brighter and a little spicier.", src=["wp_roseoil", "wp_absolute", "ps_rose"]),
   "Rose de Mai": dict(say="The absolute of the centifolia rose of Grasse, picked only in May: the most prized rose of all, heady yet fresh, strongly honeyed, with a hint of berries and less spice than the damask rose.", src=["wp_centifolia", "fw_rosedemai", "fr_grasserose"]),
   "Rose Petals": dict(same="No change: the rose's smell is its petals."),
   "Moroccan Rose": dict(say="Rose grown in Morocco, in the valley around Kelaat M'Gouna, where the centifolia is grown in its greatest numbers. North African roses smell warmer and deeper than European ones: honeyed and velvety, with a slight pepperiness.", src=["pm_moroccan", "wp_centifolia", "fr_rose"]),
   "Taif Rose": dict(say="A thirty-petalled damask rose grown high in the mountains around Taif, in Saudi Arabia, and distilled into one of the most expensive oils in the world. It is darker, denser, spicier and more honeyed than European roses, with a touch of saffron and clove.", src=["th_taif", "ith_taif", "pp_taif"]),
   "Bulgarian Rose Absolute": dict(say="Absolute of the damask rose from Bulgaria's Valley of Roses, which grows most of the world's rose oil. It smells the most like a living rose, with a wine-like, faintly lemony freshness.", src=["wp_roseoil", "bn_rose", "la_douleur"]),
   "Turkish Rose Absolute": dict(say="Absolute of the damask rose from Turkey: a little stronger and sweeter than the Bulgarian, with a note of dried tea leaves in it.", src=["bn_rose", "tg_turkrose", "la_douleur"]),
  }),
 "note-snowdrops": dict(
  say="The small, nodding white flowers that come up through the snow at the very end of winter. Up close, and especially in a large drift, they give off a faint, sweet honey smell, the nectar they make for the first bees. No oil is made from them; in a perfume they bring a cold, clean, first-flower-of-the-year sweetness.",
  src=["rhs_snowdrop", "arun_snowdrop", "at_deity"]),
 "note-tiare-flower": dict(
  say="The Tahitian gardenia, symbol of Tahiti, soaked in coconut oil to make monoi. It is heady and intensely sweet, creamy and tropical, close to gardenia and tuberose but greener and more watery-fresh. The coconut people think of belongs to monoi, not to the flower itself.",
  src=["fr_tiare", "wp_tiare", "ps_tiare", "wp_monoi"]),
 "note-tobacco-flower": dict(
  say="The white, trumpet-shaped flowers of ornamental tobacco plants, which scent the garden at night. Nothing like smoke or cigars: they smell sweet and opulent, dry-floral and a little like hay and leather, with hints of violet, clove and dried fruit.",
  src=["fr_tobblossom", "fr_whitetob", "tg_tobflower"]),
 "note-tuberose": dict(
  say="The most voluptuous white flower of all: a few stems can fill a room for days. Its absolute is rich, creamy and narcotic, sweet like honey and even gingerbread, green and a little medicinal like wintergreen, with coconut-milk creaminess and a warm, skin-like, almost indecent depth. It is the heart of the big white florals.",
  src=["fr_tube", "ps_tube", "fr_tubenews"]),
 "note-violet": dict(
  say="The small purple flower of spring, and the sweetest, most powdery floral there is: soft and romantic, airy and dewy, like old-fashioned sweets and face powder, a little like iris. The flower gives almost nothing, so its smell comes from ionones, molecules found in 1893 that are now in nearly every perfume; too much of them can briefly numb the nose.",
  src=["fr_violet", "ps_violet", "ps_ionone"]),
 "note-waterlily": dict(
  say="The flat-leaved flower of ponds, imagined in a bottle: fresh, soft and watery, green and clean, a light floral floating on water. It softens aquatic perfumes and makes them feel elegant rather than marine.",
  src=["fr_waterlily", "ps_waterlily", "ps_aquatic"]),
 "note-white-lotus": dict(
  say="The white form of the sacred lotus. As a note it is usually light and airy, watery and softly sweet, a floral floating on still water; extracted, the real flower turns out dense, dark and honeyed. White lotus in a perfume is nearly always the sheer, aquatic kind.",
  src=["fr_lotus", "tg_whitelotus", "fw_pinklotus"]),
 "note-yellow-flowers": dict(
  say="Flowers that are literally yellow, ylang-ylang, mimosa, narcissus, frangipani, used together: sweet, waxy and a little heady, with a powdery, pollen-like softness and a sunny, optimistic brightness. It is a mood of colour more than a single flower.",
  src=["fr_yellow", "fr_yellowcascade", "fr_brighter"]),
 "note-ylang-ylang": dict(
  say="The drooping, star-shaped yellow flower of a tree from the Philippines and Indonesia, distilled in stages into different grades, the first and finest the fruitiest. It is rich, heady and sweet, buttery and custard-like, with banana, jasmine and a touch of something medicinal or rubbery. It makes white florals lush and golden.",
  src=["fr_ylang", "ps_ylang", "wp_cananga", "fw_ylang"],
  vars={"Ylang-Ylang": dict(same=SAME)}),
}
out("FLO2", S, N)
