from acc import out, SAME
S = {
 "ps_allspice": ("https://perfumesociety.org/ingredients-post/allspice/", "Allspice - The Perfume Society"),
 "fw_pimento": ("https://fraterworks.com/products/pimento-oil", "Pimento Berry Oil – Fraterworks"),
 "oz_pimento": ("https://www.osmoz.com/encyclopedia/raw-materials/spice/118/pimento--jamaica-pepper-pimento-officinalis", "Pimento - Jamaica Pepper (Pimento Officinalis) Perfumes raw material - Pimento - Jamaica Pepper (Pimento Officinalis) Scent"),
 "fr_anise": ("https://www.fragrantica.com/notes/Anise-393.html", "Anise perfume ingredient, Anise fragrance and essential oils Pimpinella anisum"),
 "ps_anise": ("https://perfumesociety.org/ingredients-post/anise/", "Anise - The Perfume Society"),
 "fr_aniselic": ("https://www.fragrantica.com/news/Anise-Star-Anise-Licorice-19838.html", "Anise, Star Anise, Licorice ~ Fragrance Reviews ~ Fragrantica"),
 "pf_anethole": ("https://www.perfumerflavorist.com/fragrance/ingredients/article/21860882/anethole", "Anethole | Perfumer & Flavorist"),
 "sc_bpepper": ("https://www.scentspiracy.com/fragrance-ingredients/p/black-pepper", "Black Pepper Oil (8006-82-4) – Natural Spicy Woody Ingredient for Perfumery — Scentspiracy"),
 "fr_pepper": ("https://www.fragrantica.com/notes/Pepper-158.html", "Pepper perfume ingredient, Pepper fragrance and essential oils Piper nigrum (Piperaceae)"),
 "ps_bpepper": ("https://perfumesociety.org/ingredients-post/black-pepper/", "Black pepper - The Perfume Society"),
 "fr_caraway": ("https://www.fragrantica.com/notes/Caraway-121.html", "Caraway perfume ingredient, Caraway fragrance and essential oils Carum carvi"),
 "fw_caraway": ("https://fraterworks.com/products/caraway-seed-superior-oil", "Caraway Seed “Superior” Oil – Fraterworks"),
 "wp_carvone": ("https://en.wikipedia.org/wiki/Carvone", "Carvone - Wikipedia"),
 "fr_carawaynews": ("https://www.fragrantica.com/news/Caraway-in-your-spice-cabinet-2276.html", "Caraway - in your spice cabinet ~ Raw Materials ~ Fragrantica"),
 "fr_cardamom": ("https://www.fragrantica.com/notes/Cardamom-63.html", "Cardamom perfume ingredient, Cardamom fragrance and essential oils Elletaria Cardamomum"),
 "sc_cardamom": ("https://www.scentspiracy.com/fragrance-ingredients/p/cardamom-oil", "Cardamom Oil — Natural Ingredient for Perfumery — Scentspiracy"),
 "sc_cardguat": ("https://www.scentspiracy.com/fragrance-ingredients/p/cardamom-sfe", "Cardamom Guatemala SFE CO2 Extract (CAS 8000-66-6) – Premium Natural Ingredient for Perfumery — Scentspiracy"),
 "tg_cardguat": ("https://www.thegoodscentscompany.com/data/es1618841.html", "elettaria cardamomum seed oil guatemala, 8000-66-6", "The Good Scents Company"),
 "fr_cassia": ("https://www.fragrantica.com/notes/Cassia-60.html", "Cassia perfume ingredient, Cassia fragrance and essential oils Cinnamomum cassia"),
 "st_cassia": ("https://www.scentree.co/en/Cassia_oil.html", "ScenTree - Cassia oil (CAS N° 8007-80-5)"),
 "st_cinnamald": ("https://www.scentree.co/en/Cinnamaldehyde.html", "ScenTree - Cinnamaldehyde (CAS N° 104-55-2)"),
 "pf_chili": ("https://www.perfumerflavorist.com/flavor/savory-applications/article/21856948/theres-chemistry-in-them-chili-peppers", "There's Chemistry in Them Chili Peppers! | Perfumer & Flavorist"),
 "fr_greenpepper": ("https://www.fragrantica.com/notes/Green-Pepper-488.html", "Green Pepper perfume ingredient, Green Pepper fragrance and essential oils Capsicum annuum"),
 "fr_vestibule": ("https://www.fragrantica.com/perfume/Ataraxia-Perfumery/Vestibule-100362.html", "Vestibule Ataraxia Perfumery perfume - a fragrance for women and men"),
 "cpm_reaper": ("https://www.chilipeppermadness.com/chili-pepper-types/carolina-reaper/", "Carolina Reaper", "Chili Pepper Madness"),
 "fr_cinnamon": ("https://www.fragrantica.com/notes/Cinnamon-65.html", "Cinnamon perfume ingredient, Cinnamon fragrance and essential oils Cinnamomum verum"),
 "sc_cinnamon": ("https://www.scentspiracy.com/fragrance-ingredients/p/cinnamon-oil", "Cinnamon Oil (8015-91-6) – Natural Warm-Spicy Ingredient for Perfumery — Scentspiracy"),
 "fr_cinnamonnews": ("https://www.fragrantica.com/news/Cinnamon-in-the-Kitchen-and-in-Perfumery-13697.html", "Cinnamon in the Kitchen and in Perfumery ~ Raw Materials ~ Fragrantica"),
 "wp_cinnamon": ("https://en.wikipedia.org/wiki/Cinnamon", "Cinnamon - Wikipedia"),
 "wp_attar": ("https://en.wikipedia.org/wiki/Attar", "Attar - Wikipedia"),
 "fw_attars": ("https://fraterworks.com/a/library/oils-and-attars-of-oriental-and-indian-perfumery", "Oils and Attars of Oriental and Indian Perfumery – Fraterworks"),
 "pw_list": ("https://pinewardperfume.com/pages/master-scent-list", "Master Scent List", "Pineward"),
 "la_walk": ("https://lesabstraits.com/products/philosophers-walk", "Philosopher's Walk", "Les Abstraits"),
 "fr_cloves": ("https://www.fragrantica.com/notes/Cloves-61.html", "Cloves perfume ingredient, Cloves fragrance and essential oils Eugenia Caryophyllata"),
 "sc_clove": ("https://www.scentspiracy.com/naturals/clove-buds-oil", "Clove Bud Oil (CAS 8000-34-8) – Premium Natural Spicy-Aromatic Ingredient for Perfumery — Scentspiracy"),
 "fr_carnclove": ("https://www.fragrantica.com/news/Carnation-and-Clove-13400.html", "Carnation and Clove ~ Raw Materials ~ Fragrantica"),
 "sc_coriander": ("https://www.scentspiracy.com/fragrance-ingredients/p/coriander-seed-oil", "Coriander Seed Oil (CAS 8008-52-4) – Premium Natural Ingredient for Perfumery — Scentspiracy"),
 "fr_coriander": ("https://www.fragrantica.com/notes/Coriander-64.html", "Coriander perfume ingredient, Coriander fragrance and essential oils Coriandrum sativum"),
 "fw_coriander": ("https://fraterworks.com/products/coriander-seed-oil", "Coriander Seed Oil – Fraterworks"),
 "fr_cumin": ("https://www.fragrantica.com/notes/Cumin-549.html", "Cumin perfume ingredient, Cumin fragrance and essential oils Cuminum cyminum"),
 "fr_cuminnews": ("https://www.fragrantica.com/news/CUMIN-Polarizing-Note-of-Sweat-Intimacy-3722.html", "CUMIN: Polarizing Note of Sweat & Intimacy ~ Raw Materials ~ Fragrantica"),
 "fw_cumin": ("https://fraterworks.com/products/cumin-oil", "Cumin Seed Oil – Fraterworks"),
 "wp_sotolon": ("https://en.wikipedia.org/wiki/Sotolon", "Sotolon - Wikipedia"),
 "fr_fenugreek": ("https://www.fragrantica.com/notes/Fenugreek-475.html", "Fenugreek perfume ingredient, Fenugreek fragrance and essential oils Trigonella foenum-graecum"),
 "fw_fenugreek": ("https://fraterworks.com/products/fenugreek-absolute-90-ipm", "Fenugreek “Signature” Absolute – Fraterworks"),
 "ps_fenugreek": ("https://perfumesociety.org/ingredients-post/fenugreek/", "Fenugreek - The Perfume Society"),
 "fr_ginger": ("https://www.fragrantica.com/notes/Ginger-62.html", "Ginger perfume ingredient, Ginger fragrance and essential oils Zingiber officinale"),
 "ps_ginger": ("https://perfumesociety.org/ingredients-post/ginger/", "Ginger - The Perfume Society"),
 "fr_gingernews": ("https://www.fragrantica.com/news/Ginger-in-Life-and-in-Perfume-18135.html", "Ginger in Life and in Perfume ~ Raw Materials ~ Fragrantica"),
 "fw_gingercote": ("https://fraterworks.com/products/ginger-oil-cote-divoire", "Ginger Oil Fresh, Côte d'Ivoire – Fraterworks"),
 "fw_gingertop": ("https://fraterworks.com/products/ginger-top-note-co2", "Ginger \"Top Note\" CO2, P. Jungle Essence – Fraterworks"),
 "la_belle": ("https://lesabstraits.com/products/belle-ame", "Belle Âme", "Les Abstraits"),
 "adar_amber": ("https://adarperfumes.com/products/amber-zero-essence-of-dephts", "Amber Zero: Essence of Depths", "ADAR Perfumes"),
 "fr_nutmeg": ("https://www.fragrantica.com/notes/Nutmeg-59.html", "Nutmeg perfume ingredient, Nutmeg fragrance and essential oils Myristica fragrans"),
 "fr_nutmegnews": ("https://www.fragrantica.com/news/Nutmeg-A-Fragrant-Fragrancer-19300.html", "Nutmeg: A Fragrant Fragrancer ~ Raw Materials ~ Fragrantica"),
 "sc_nutmeg": ("https://www.scentspiracy.com/fragrance-ingredients/p/nutmeg-oil", "Nutmeg Oil (CAS: 84082-68-8) – Premium Warm Natural Ingredient for Perfumery — Scentspiracy"),
 "fr_pinkpepper": ("https://www.fragrantica.com/notes/Pink-Pepper-91.html", "Pink Pepper perfume ingredient, Pink Pepper fragrance and essential oils Schinus molle (Anacardiaceae)"),
 "ps_pinkpepper": ("https://perfumesociety.org/ingredients-post/pink-pepper/", "Pink pepper - The Perfume Society"),
 "fr_pinkpeppernews": ("https://www.fragrantica.com/news/Note-du-Jour-Pink-Pepper-4610.html", "Note du Jour: Pink Pepper ~ Raw Materials ~ Fragrantica"),
 "fr_saffron": ("https://www.fragrantica.com/notes/Saffron-55.html", "Saffron perfume ingredient, Saffron fragrance and essential oils Crocus Sativus Linneaus"),
 "ps_saffron": ("https://perfumesociety.org/ingredients-post/saffron/", "Saffron - The Perfume Society"),
 "fw_safranal": ("https://fraterworks.com/products/safranal", "Safranal – Fraterworks"),
 "ks_saffron": ("https://kashmiril.com/blogs/journal/kashmiri-saffron-vs-iranian-saffron", "Kashmiri Saffron vs Iranian Saffron", "Kashmiril"),
 "scroll_saffron": ("https://scroll.in/article/953651/amid-declining-production-kashmiri-farmers-seek-geographical-indication-tag-for-local-saffron", "Amid Declining Production, Kashmiri Farmers Seek Geographical Indication Tag for Local Saffron", "Scroll.in"),
 "fr_spicy": ("https://www.fragrantica.com/notes/Spicy-Notes-321.html", "Spicy Notes perfume ingredient, Spicy Notes fragrance and essential oils"),
 "ps_woodyspicy": ("https://perfumesociety.org/fragrance-families/woody/spicy/", "Woody spicy - The Perfume Society"),
 "ps_feelingspicy": ("https://perfumesociety.org/fragrances-for-feeling-spicy/", "Fragrances for... Feeling Spicy - The Perfume Society"),
 "fr_turmeric": ("https://www.fragrantica.com/notes/Curcuma-Turmeric-308.html", "Curcuma (Turmeric) perfume ingredient, Curcuma (Turmeric) fragrance and essential oils Curcuma longa"),
 "fr_turmericnews": ("https://www.fragrantica.com/news/Turmeric-A-Note-To-Watch-14163.html", "Turmeric: A Note To Watch ~ Fragrance Reviews ~ Fragrantica"),
 "tg_turmeric": ("https://www.thegoodscentscompany.com/odor/turmeric.html", "The Good Scents Company -Odor Descriptor Listing for turmeric", "The Good Scents Company"),
 "fr_wasabi": ("https://www.fragrantica.com/notes/Wasabi-662.html", "Wasabi perfume ingredient, Wasabi fragrance and essential oils Eutrema japonicum"),
 "ps_wasabi": ("https://perfumesociety.org/olfactive-studios-panoramic-perfume-added-wasabi-2/", "Olfactive Studio's panoramic perfume - with added wasabi! - The Perfume Society"),
 "ns_waterpepper": ("https://www.naturespot.org/node/22875", "Water-pepper - Persicaria hydropiper", "NatureSpot"),
 "fn_waterpepper": ("https://mail.first-nature.com/flowers/persicaria-hydropiper.php", "Persicaria hydropiper - Water-pepper", "First Nature"),
}
N = {
 "note-allspice": dict(
  say="The dried berry of a Jamaican tree, named because it smells like several spices at once: cinnamon, clove and nutmeg together, sweet and dry, warm and a little peppery. It is sweeter and longer-lasting than clove, and it sits beautifully with rose and other spices, warming carnation, floral and men's perfumes.",
  src=["ps_allspice", "fw_pimento", "oz_pimento"]),
 "note-anise": dict(
  say="The sweet, liquorice smell of aniseed, star anise and fennel, which share one molecule, anethole. It is sweet and warm, herbal and a little like root beer, the flavour of pastis, ouzo and liquorice sweets. In a perfume it adds a sweet, slightly medicinal spice and sits well with lavender, citrus and woods.",
  src=["fr_anise", "ps_anise", "fr_aniselic", "pf_anethole"]),
 "note-black-pepper": dict(
  say="Freshly cracked peppercorns: hot and fresh, dry and woody, almost tingling to sniff, with a citrusy lift. The oil does not burn, because the molecule that makes pepper hot does not evaporate; what you smell is its warm, woody-spicy aroma. It brightens the top of many men's perfumes and adds texture and radiance to woods and florals.",
  src=["sc_bpepper", "fr_pepper", "ps_bpepper"],
  vars={"Pepper": dict(same="No change: pepper in a list of notes means black pepper.")}),
 "note-caraway": dict(
  say="The small crescent seeds of rye bread and aquavit. Their oil is mostly carvone, which in caraway's form smells warm, spicy and a little minty-herbal, exactly like fresh rye bread. It gives a perfume a savoury, bakery warmth, and it hides in several famous ones, Le Male among them.",
  src=["fr_caraway", "fw_caraway", "wp_carvone", "fr_carawaynews"]),
 "note-cardamom": dict(
  say="The green pods of chai and Scandinavian buns. Its oil opens cool and fresh, a little like eucalyptus and mint, then turns warm, sweet and aromatic, spicy with a soft balsamic and floral finish. It is a fresh spice rather than a hot one, and it brightens rose, woods and ambery perfumes alike.",
  src=["fr_cardamom", "sc_cardamom", "sc_cardguat"],
  vars={
   "Guatemalan Cardamom": dict(say="Cardamom from Guatemala, the finest source. Its oil holds more of the sweet, spicy ester that gives cardamom its warmth, and less of the camphor, so it is sweeter, smoother and less medicinal than Indian cardamom.", src=["sc_cardguat", "tg_cardguat"]),
  }),
 "note-cassia": dict(
  say="Chinese cinnamon, the bark most 'cinnamon' in shops really is. It is almost all cinnamaldehyde, so it smells hot, sweet and cinnamon-red, rougher and less subtle than true cinnamon, with a resinous, smoky, honeyed richness that perfumers use to warm florals and ambers.",
  src=["fr_cassia", "st_cassia", "st_cinnamald"]),
 "note-chilli": dict(
  say="The heat of a chilli barely has a smell, since the molecule that burns does not float in the air. As a note chilli is therefore an impression: a hot, fiery, red spice, peppery and a little green like a fresh capsicum, used to give a perfume a feeling of heat and danger.",
  src=["pf_chili", "fr_greenpepper", "fr_vestibule"],
  vars={
   "Red Hot Chilli": dict(say="Chilli named for its colour and its heat: ripe red chilli, sweeter and fruitier than a green one, with the idea of fire turned up. It is an impression rather than a different material.", src=["fr_vestibule", "pf_chili"]),
   "Carolina Reaper": dict(say="Once the world's hottest chilli, bred in South Carolina, over a million units on the Scoville scale. Its flavour is surprisingly fruity and sweet before the fire; as a note it stands for heat taken as far as it can go.", src=["cpm_reaper", "fr_vestibule"]),
  }),
 "note-cinnamon": dict(
  say="The rolled bark of the cinnamon tree: warm, sweet and spicy, with a hot red bite and a soft, woody sweetness, the smell of baking and mulled wine. True cinnamon from Sri Lanka is smoother and more complex than its cheaper cousin cassia. It warms oriental, gourmand and floral perfumes.",
  src=["fr_cinnamon", "sc_cinnamon", "fr_cinnamonnews"],
  vars={
   "Cinnamon (Ceylon)": dict(say="True cinnamon, from Sri Lanka (once Ceylon), rather than cassia. It has less cinnamaldehyde than cassia but smells finer: smoother, sweeter and more complex, with fruity top notes, where cassia is harsher and hotter.", src=["sc_cinnamon", "st_cinnamald", "la_walk"]),
   "Cinnamon Attar": dict(say="Cinnamon made as an attar, the old Indian way: distilled with water in a copper still into a vessel of sandalwood oil and left to age. So the spice comes on a soft, creamy woody base, rounder and longer-lasting than cinnamon oil alone.", src=["wp_attar", "fw_attars", "pw_list"]),
  }),
 "note-clove": dict(
  say="The dried flower buds of the clove tree: intensely warm and spicy, sweet and woody, a little medicinal, one of the most powerful natural materials a perfumer has. Most of it is eugenol, which it shares with carnation, so clove sits behind many carnation and rose accords, as well as ambers, spices and men's perfumes.",
  src=["fr_cloves", "sc_clove", "fr_carnclove"],
  vars={"Cloves": dict(same=SAME)}),
 "note-coriander": dict(
  say="The seed, not the leaf: coriander seed oil is mostly linalool, so it smells clean, soft and elegant, peppery and woody at first, then warmly floral, almost sweet like a sweet shop. It is a fresh spice that links the top of a perfume to its warmer heart, and it blends into colognes, chypres and ambers.",
  src=["sc_coriander", "fr_coriander", "fw_coriander"]),
 "note-cumin": dict(
  say="The earthy spice of curries, and perfumery's most divisive one. It is sharp, green and pungent at first, then warm and resinous, and then unmistakably like skin and sweat: an intimate, animal warmth. People love it or hate it; used well it makes a perfume feel human and sensual.",
  src=["fr_cumin", "fr_cuminnews", "fw_cumin"],
  vars={"Cumin Seed Oil": dict(same="No change: cumin oil is distilled from the seeds anyway.")}),
 "note-fenugreek": dict(
  say="Small golden seeds used in curries, and a smell that changes with strength: strong it is savoury, like curry; diluted it turns sweet, nutty and like maple syrup and burnt sugar. Both come from one molecule, sotolon. In perfume it brings a gourmand, maple sweetness with a strange, spicy edge.",
  src=["wp_sotolon", "fr_fenugreek", "fw_fenugreek", "ps_fenugreek"]),
 "note-ginger": dict(
  say="The knobbly root: warm but fresh, spicy and bracing, almost nose-tingling, with a lemony brightness at the top and a sweet, woody, almost balsamic depth. It lifts a perfume and pairs as easily with citrus and woods as with vanilla and white flowers.",
  src=["fr_ginger", "ps_ginger", "fr_gingernews"],
  vars={
   "African Ginger": dict(say="Ginger from West Africa, prized for its quality: brighter and more dazzling than ginger from Asia, with all the fresh ginger character and none of the dustiness.", src=["fw_gingercote", "la_belle"]),
   "Fresh Ginger": dict(say="Ginger as the freshly cut root rather than the dried, cooked spice: sharp, lemony and fizzy, bright and juicy, where ginger oil distilled from dried root is heavier and warmer.", src=["fw_gingertop", "pw_list", "fr_ginger"]),
   "Ginger Root": dict(same="No change: ginger is a root, and its oil comes from it."),
   "Icy Ginger": dict(say="Not a different ginger but ADAR's word for it: ginger's cool, sparkling, lemony top turned up, so it feels crisp and cold rather than warm and spicy.", src=["adar_amber", "fw_gingertop"]),
  }),
 "note-nutmeg": dict(
  say="The seed of a tropical tree, grated over custard and eggnog. Its oil is fresh and warm at once: a light, piney top, then a sweet-spicy, woody heart, a little nutty and lemony. It is a subtler warmth than cinnamon and clove, and a classic in fougères, colognes and orientals.",
  src=["fr_nutmeg", "fr_nutmegnews", "sc_nutmeg"]),
 "note-pink-pepper": dict(
  say="Not a true pepper but the pink berries of a South American tree. It is sparkling rather than hot: fresh and fruity, a little citrusy, with a rosy, woody sweetness, quite different from the tingle of black pepper. Since the mid-1990s it has become one of the most common opening notes in perfumery.",
  src=["fr_pinkpepper", "ps_pinkpepper", "fr_pinkpeppernews"],
  vars={"Baie Rose": dict(same="No change: baie rose is simply pink pepper in French.")}),
 "note-saffron": dict(
  say="The red threads of the crocus, the costliest spice in the world. Its smell is strange and beautiful: sweet and bittersweet, leathery and medicinal like iodine, with hay, honey and a faint metallic edge, from its molecule safranal. It is warm and intimate, and a signature of oriental and oud perfumes.",
  src=["fr_saffron", "ps_saffron", "fw_safranal"],
  vars={
   "Indian Saffron": dict(say="Saffron from India, above all Kashmir, grown in far smaller amounts than Iran's. Kashmiri threads are among the darkest and hold more safranal, the aroma molecule, and are thought richer in colour and scent.", src=["ks_saffron", "scroll_saffron"]),
  }),
 "note-spices": dict(
  say="No single spice: a blend of them, which can be warm, like cinnamon, clove, nutmeg and pepper, or fresh, like ginger, coriander and cardamom. Warm spices make a perfume cosy and rich; fresh ones make it bright and tingling.",
  src=["fr_spicy", "ps_woodyspicy", "ps_feelingspicy"],
  vars={"Spice": dict(same=SAME)}),
 "note-turmeric": dict(
  say="The golden root of curries. Its smell is warm and earthy, woody and a little like carrot, with a peppery ginger zing at the back. It is rare in perfume because it does not sweeten easily, and it brings an earthy, slightly dusty warmth.",
  src=["fr_turmeric", "fr_turmericnews", "tg_turmeric"]),
 "note-wasabi": dict(
  say="The Japanese green root served with sushi, hot like mustard rather than chilli, with vapours that go straight up your nose. In perfume it is green, peppery and fresh, a tremble of sharpness that makes a green note pop, though it is hard to catch.",
  src=["fr_wasabi", "ps_wasabi"]),
 "note-water-pepper": dict(
  say="A small wild plant of riverbanks and damp meadows, whose leaves taste sharply of pepper and give off a pungent smell when crushed. That bite comes from polygodial, not from black pepper's piperine. As a note it is a wild, green, peppery sharpness.",
  src=["ns_waterpepper", "fn_waterpepper"]),
}
out("SPI", S, N)
