from acc import out, SAME
S = {
 "adar_incantu": ("https://adarperfumes.com/products/incantu-drops-of-styx", "Incantu: Drops of Styx", "ADAR Perfumes"),
 "fr_agarwood": ("https://www.fragrantica.com/notes/Agarwood-Oud-114.html", "Agarwood (Oud) perfume ingredient, Agarwood (Oud) fragrance and essential oils Aquilaria agallocha i A. malaccensis (Thymelaeaceae)"),
 "fr_rojaamber": ("https://www.fragrantica.com/perfume/Roja-Dove/Amber-Aoud-17931.html", "Amber Aoud Roja Dove perfume - a fragrance for women and men 2012"),
 "fr_amberwood": ("https://www.fragrantica.com/notes/Amberwood-691.html", "Amberwood perfume ingredient, Amberwood fragrance and essential oils"),
 "sc_amberwood": ("https://www.scentspiracy.com/fragrance-ingredients/p/amberwood", "Amberwood F / Boisambrene Forte (CAS 58567-11-6) – Premium Synthetic Ingredient for Perfumery — Scentspiracy"),
 "fr_amberwoodboard": ("https://www.fragrantica.com/board/viewtopic.php?id=312168", "How do you perceive amberwood? (Page 1) — General Perfume Talk — Fragrantica Club", "Fragrantica Club"),
 "fw_amyris": ("https://fraterworks.com/products/amyris-signature-oil-haiti", "Amyris “Signature” Oil, Haiti – Fraterworks"),
 "oz_amyris": ("https://www.osmoz.com/encyclopedia/raw-materials/wood/89/amyris-amyris-balsamifera", "Amyris (Amyris Balsamifera) Perfumes raw material - Amyris (Amyris Balsamifera) Scent"),
 "fr_amyris": ("https://www.fragrantica.com/notes/Amyris-416.html", "Amyris perfume ingredient, Amyris fragrance and essential oils Amyris balsamifera"),
 "fr_bark": ("https://www.fragrantica.com/notes/Bark-709.html", "Bark perfume ingredient, Bark fragrance and essential oils"),
 "fr_woody": ("https://www.fragrantica.com/notes/Woody-Notes-315.html", "Woody Notes perfume ingredient, Woody Notes fragrance and essential oils"),
 "fr_birch": ("https://www.fragrantica.com/notes/Birch-31.html", "Birch perfume ingredient, Birch fragrance and essential oils Betula, family Betulaceae"),
 "fr_birchnews": ("https://www.fragrantica.com/news/Birch-4522.html", "Birch ~ Fragrances and Cultures ~ Fragrantica"),
 "prin_haxan": ("https://prinlomros.com/product/haxan/", "Haxan", "PRIN"),
 "fr_cashmeran": ("https://www.fragrantica.com/notes/Cashmeran-348.html", "Cashmeran perfume ingredient, Cashmeran fragrance and essential oils"),
 "ps_cashmeran": ("https://perfumesociety.org/ingredients-post/cashmeran/", "Cashmeran - The Perfume Society"),
 "wp_cashmeran": ("https://en.wikipedia.org/wiki/Cashmeran", "Cashmeran - Wikipedia"),
 "ps_cedar": ("https://perfumesociety.org/ingredients-post/cedar/", "Cedarwood - The Perfume Society"),
 "fr_cedar": ("https://www.fragrantica.com/notes/Cedar-41.html", "Cedar perfume ingredient, Cedar fragrance and essential oils Cedrus, family Pinaceae"),
 "fr_cedarnews": ("https://www.fragrantica.com/news/Cedar-In-Perfumery-Roots-and-Stumps-10560.html", "Cedar In Perfumery: Roots and Stumps ~ Raw Materials ~ Fragrantica"),
 "fr_cedarboard": ("https://www.fragrantica.com/board/viewtopic.php?id=305020", "Virginia vs Atlas vs Himalaya Cedar - how do you tell them apart? (Page 1) — Perfume Selection Tips for Men — Fragrantica Club", "Fragrantica Club"),
 "tg_atlas": ("https://www.thegoodscentscompany.com/data/es1028531.html", "atlas cedarwood oil, 8023-85-6", "The Good Scents Company"),
 "tg_himalaya": ("https://www.thegoodscentscompany.com/data/es1031791.html", "cedarwood oil himalaya, 68991-36-6", "The Good Scents Company"),
 "la_douleur": ("https://lesabstraits.com/products/la-douleur-exquise", "La Douleur Exquise", "Les Abstraits"),
 "pw_list": ("https://pinewardperfume.com/pages/master-scent-list", "Master Scent List", "Pineward"),
 "fr_extract": ("https://www.fragrantica.com/news/From-Tincture-To-Supercritical-Extraction-Methods-Of-Natural-Aroma-Extraction-8724.html", "From Tincture To Supercritical Extraction — Methods Of Natural Aroma Extraction ~ Raw Materials ~ Fragrantica"),
 "adar_aeth": ("https://adarperfumes.com/products/aetherialism-storm-breath", "Aetherialism: Storm Breath", "ADAR Perfumes"),
 "pw_gristmill": ("https://pinewardperfume.com/products/gristmill", "Gristmill", "Pineward"),
 "fr_gristmill": ("https://www.fragrantica.com/perfume/Pineward-Perfumes/Gristmill-83385.html", "Gristmill Pineward Perfumes perfume - a fragrance for women and men"),
 "fr_sawdust": ("https://www.fragrantica.com/notes/Sawdust-1214.html", "Sawdust perfume ingredient, Sawdust fragrance and essential oils"),
 "tg_sawdust": ("https://thegoodscentscompany.com/odor/sawdust.html", "The Good Scents Company -Odor Descriptor Listing for sawdust", "The Good Scents Company"),
 "ps_pencil": ("https://perfumesociety.org/to-the-pulse-point-the-scent-of-pencil-shavings-back-to-school-nostalgia/", "Straight to the (pulse) point: the scent of pencil shavings & 'back to school' nostalgia - The Perfume Society"),
 "fr_cypriol": ("https://www.fragrantica.com/notes/Cypriol-Oil-or-Nagarmotha-406.html", "Cypriol Oil or Nagarmotha perfume ingredient, Cypriol Oil or Nagarmotha fragrance and essential oils Cyperus scariosus"),
 "fw_cypriol": ("https://fraterworks.com/products/cypriol-nagarmotha-oil", "Cypriol “Signature” Oil – Fraterworks"),
 "st_cypriol": ("https://www.scentree.co/en/Cypriol_oil.html", "ScenTree - Cypriol oil (CAS N° 68916-60-9)"),
 "fr_guaiac": ("https://www.fragrantica.com/notes/Guaiac-Wood-36.html", "Guaiac Wood perfume ingredient, Guaiac Wood fragrance and essential oils Bulnesia sarmienti"),
 "ps_guaiac": ("https://perfumesociety.org/ingredients-post/guaiac-wood/", "Guaiac Wood - The Perfume Society"),
 "fw_guaiac": ("https://fraterworks.com/products/guaiac-wood-oil", "Guaiac Wood Oil – Fraterworks"),
 "fr_mahogany": ("https://www.fragrantica.com/notes/Mahogany-43.html", "Mahogany perfume ingredient, Mahogany fragrance and essential oils Swietenia Macrophylla"),
 "oz_mahogany": ("https://www.osmoz.com/encyclopedia/raw-materials/wood/103/mahogany-swietenia-mahogani", "Mahogany (Swietenia mahogani) Perfumes raw material - Mahogany (Swietenia mahogani) Scent"),
 "tb_coffin": ("https://tombstonefragrances.shop/products/product_96dfccf6-9558-1964-5d89-1505be7abf53", "Sweet Coffin", "TOMBSTONE"),
 "fr_oak": ("https://www.fragrantica.com/notes/Oak-326.html", "Oak perfume ingredient, Oak fragrance and essential oils Quercus"),
 "ps_oak": ("https://perfumesociety.org/ingredients-post/oak/", "Oak - The Perfume Society"),
 "oz_oak": ("https://www.osmoz.com/encyclopedia/raw-materials/wood/88/oak-quercus-robur", "Oak (Quercus Robur) Perfumes raw material - Oak (Quercus Robur) Scent"),
 "wp_agarwood": ("https://en.wikipedia.org/wiki/Agarwood", "Agarwood - Wikipedia"),
 "pf_agarwood": ("https://www.perfumerflavorist.com/fragrance/ingredients/article/21856933/king-of-scents-agarwood", "King of Scents — Agarwood | Perfumer & Flavorist"),
 "fr_oudterroir": ("https://www.fragrantica.com/news/OUD-SERIES-The-Smell-of-Oud-by-Terroir-5253.html", "OUD SERIES: The Smell of Oud by Terroir ~ Raw Materials ~ Fragrantica"),
 "fr_oudmirror": ("https://www.fragrantica.com/news/Oud-The-Mirror-of-the-Land-26126.html", "Oud: The Mirror of the Land ~ Columns ~ Fragrantica"),
 "cfb_oud": ("https://cafleurebon.com/notes-from-the-lab-oud-and-terroir-plus-choose-your-oud-giveaway/", "Notes From the Lab: Oud and Terroir", "CaFleureBon"),
 "fr_cambodianoud": ("https://www.fragrantica.com/notes/Cambodian-Oud-762.html", "Cambodian Oud perfume ingredient, Cambodian Oud fragrance and essential oils Aquilaria agallocha"),
 "fr_ancientoud": ("https://www.fragrantica.com/perfume/Grande/Ancient-Oud-124253.html", "Ancient Oud Grande perfume - a fragrance for women and men"),
 "adar_lignum": ("https://adarperfumes.com/products/lignum-dei-the-wood-of-god-essence-of-hope-micro-batch-77-pieces", "Lignum Dei: The Wood of God", "ADAR Perfumes"),
 "adar_odds": ("https://adarperfumes.com/products/against-all-odds", "Against All Odds", "ADAR Perfumes"),
 "ps_patch": ("https://perfumesociety.org/ingredients-post/patchouli/", "Patchouli - The Perfume Society"),
 "fr_patch": ("https://www.fragrantica.com/notes/Patchouli-34.html", "Patchouli perfume ingredient, Patchouli fragrance and essential oils Pogostemon Cablin"),
 "wp_patch": ("https://en.wikipedia.org/wiki/Patchouli", "Patchouli - Wikipedia"),
 "fw_patchdark": ("https://fraterworks.com/products/patchouli-dark", "Patchouli Dark PA30 – Fraterworks"),
 "fw_patchlight": ("https://fraterworks.com/products/patchouli-light", "Patchouli Light Aceh PA38 – Fraterworks"),
 "la_walk": ("https://lesabstraits.com/products/philosophers-walk", "Philosopher's Walk", "Les Abstraits"),
 "ps_driftwood": ("https://perfumesociety.org/ingredients-post/driftwood/", "Driftwood - The Perfume Society"),
 "fr_driftwood": ("https://www.fragrantica.com/notes/Driftwood-503.html", "Driftwood perfume ingredient, Driftwood fragrance and essential oils"),
 "ukw_pine": ("https://www.ukworkshop.co.uk/threads/what-other-woods-smell-strongly-of-pine.51487/", "What Other Woods Smell Strongly of Pine?", "UKWorkshop"),
 "fww_resin": ("https://finewoodworking.com/forum/how-much-resin-is-too-much", "How Much Resin Is Too Much???", "Fine Woodworking"),
 "fr_sandal": ("https://www.fragrantica.com/notes/Sandalwood-33.html", "Sandalwood perfume ingredient, Sandalwood fragrance and essential oils Santalum Album"),
 "wp_sandaloil": ("https://en.wikipedia.org/wiki/Sandalwood_oil", "Sandalwood oil - Wikipedia"),
 "pf_indiansandal": ("https://www.perfumerflavorist.com/fragrance/ingredients/article/21856083/indian-sandalwood-returns-to-the-perfumers-palette", "Indian Sandalwood Returns to the Perfumer's Palette | Perfumer & Flavorist"),
 "wp_santalum": ("https://en.wikipedia.org/wiki/Santalum_album", "Santalum album - Wikipedia"),
 "tg_ausandal": ("https://www.thegoodscentscompany.com/data/es1050241.html", "sandalwood oil west australia (santalum spicatum), 8024-35-9", "The Good Scents Company"),
 "fr_teak": ("https://www.fragrantica.com/notes/Teak-Wood-266.html", "Teak Wood perfume ingredient, Teak Wood fragrance and essential oils Tectona"),
 "oz_teak": ("https://www.osmoz.com/encyclopedia/raw-materials/wood/105/teak-tectona-grandis", "Teak (Tectona Grandis) Perfumes raw material - Teak (Tectona Grandis) Scent"),
 "fr_vetiver": ("https://www.fragrantica.com/notes/Vetiver-2.html", "Vetiver perfume ingredient, Vetiver fragrance and essential oils Vetiveria Zizanoid"),
 "fr_vetivernews": ("https://www.fragrantica.com/news/Different-Kinds-of-Vetiver-in-Perfumery-16912.html", "Different Kinds of Vetiver in Perfumery ~ Raw Materials ~ Fragrantica"),
 "fw_vethaiti": ("https://fraterworks.com/products/vetiver-oil-haiti", "Vetiver Oil, Haiti – Fraterworks"),
 "st_vethaiti": ("https://www.scentree.co/en/Vetiver_oil_(Ha%C3%AFti).html", "ScenTree - Vetiver oil (Haïti) (CAS N° 8016-96-4)"),
 "wp_absolute": ("https://en.wikipedia.org/wiki/Absolute_(perfumery)", "Absolute (perfumery) - Wikipedia"),
 "cameo_willow": ("https://cameo.mfa.org/wiki/Willow_bark", "Willow Bark", "CAMEO, Museum of Fine Arts Boston"),
 "pp_willow": ("https://premierepeau.com/pages/glossary-terms/white-willow", "White Willow", "Premiere Peau"),
 "ps_woody": ("https://perfumesociety.org/fragrance-families/woody/", "Woody - The Perfume Society"),
 "fr_drywood": ("https://www.fragrantica.com/notes/Dry-Wood-1012.html", "Dry Wood perfume ingredient, Dry Wood fragrance and essential oils"),
 "fr_deserthope": ("https://www.fragrantica.com/perfume/Almost-Human/Desert-Hope-122264.html", "Desert Hope Almost Human perfume - a fragrance for women and men"),
}
OUD_ORIGIN = ["fr_oudterroir", "cfb_oud"]
N = {
 "note-amber-oud": dict(
  say="Oud wrapped in amber: the dark, woody, sometimes animal smell of agarwood made sweeter and warmer by an ambery, resinous, vanilla-soft base. Together they read like honey and spice, dry wood and a glowing, velvety warmth, a pairing much loved in Middle Eastern perfumery.",
  src=["adar_incantu", "fr_agarwood", "fr_rojaamber"]),
 "note-amberwood": dict(
  say="Not a tree but a family of modern synthetic woody-ambers, the best known sold as Amberwood or Boisambrene. They are very dry, diffusive and extremely long-lasting, with a warm, ambergris-like shimmer, and to many noses sharp, fuzzy or a little screechy. They are behind the huge, long-lasting woody trail of many recent perfumes.",
  src=["fr_amberwood", "sc_amberwood", "fr_amberwoodboard"]),
 "note-amyris": dict(
  say="The oil of a small Caribbean tree, often called West Indian sandalwood though it is no sandalwood at all. It smells soft and creamy-woody, sweet and balsamic, a little smoky with a vanilla finish, and it is used as an affordable stand-in for sandalwood and a gentle fixative.",
  src=["fw_amyris", "oz_amyris", "fr_amyris"]),
 "note-bark": dict(
  say="The skin of a tree: dry, dusty and woody, a little earthy and resinous, like rough bark warmed in the sun. It is an impression built from woody materials, and it makes a woody perfume feel outdoors rather than polished.",
  src=["fr_bark", "fr_woody"]),
 "note-birch": dict(
  say="The white-barked tree of northern forests. Its leaves and buds smell green; its bark and wood, and above all the tar distilled from them, smell smoky, leathery and a little like wintergreen. Birch is the traditional scent of Russian leather, and in a perfume it brings smoke, leather and cold forest.",
  src=["fr_birch", "fr_birchnews", "prin_haxan"]),
 "note-cashmeran": dict(
  say="A synthetic molecule named for the feel of cashmere: musky and woody at once, dry and 'woolly' like a new jumper, powdery and a little spicy and piney, with a clean, sun-warmed, skin-like saltiness. It makes a perfume feel soft and cosy.",
  src=["fr_cashmeran", "ps_cashmeran", "wp_cashmeran"]),
 "note-cedarwood": dict(
  say="The wood of pencils and cedar chests: dry, clean and woody, like pencil shavings, with a resinous, slightly smoky warmth. Perfumers use several cedars, and they differ: Virginian is clean and smooth, Atlas warmer and balsamic, Himalayan creamy. It is one of the most used woods in perfumery, a dependable, grounding base.",
  src=["ps_cedar", "fr_cedar", "fr_cedarnews", "fr_cedarboard"],
  vars={
   "Cedar": dict(same="No change: cedar and cedarwood mean the same note."),
   "Atlas Cedar": dict(say="True cedar from the Atlas mountains of Morocco: warmer, sweeter and more balsamic than Virginian cedar, with the smell of pencil shavings and a slightly smoky, 'dirty' depth.", src=["fr_cedarboard", "tg_atlas", "la_douleur"]),
   "Himalayan Cedar": dict(say="The deodar cedar of the Himalayas: creamier and softer than the others, almost like wood and milk mixed, with a smoky edge.", src=["fr_cedarboard", "tg_himalaya", "pw_list"]),
   "Cedar Wood Tincture": dict(say="Cedar soaked in alcohol until the alcohol takes its smell, rather than distilled: the oldest, gentlest way of extracting, which keeps a softer, rounder, more natural cedar.", src=["fr_extract", "adar_aeth"]),
   "Cedar Planks": dict(say="Cedar as cut boards in a workshop: fresh sawn wood and pencil shavings, drier and rawer than a polished cedar oil.", src=["pw_gristmill", "fr_sawdust", "ps_pencil"]),
   "Blood Cedar": dict(say="Pineward's own name, not a standard material: it points to cedar's red heartwood, a darker, deeper, more resinous cedar than the pale, clean kind.", src=["pw_list", "ps_cedar"]),
  }),
 "note-cypriol": dict(
  say="The root of an Indian sedge, nagarmotha, and a chameleon: spicy at first, like cinnamon, then earthy and green like vetiver, then woody like cedar, with a smoky breath of frankincense and campfire. It is often used to rebuild the smell of oud.",
  src=["fr_cypriol", "fw_cypriol", "st_cypriol"],
  vars={
   "Cypriol Oil or Nagarmotha": dict(same="No change: cypriol and nagarmotha are two names for the same oil."),
   "Nagarmotha": dict(same="No change: nagarmotha is cypriol's Indian name."),
  }),
 "note-edelwood-oil": dict(
  say="No perfume material by this name could be found: it seems to be Pineward's own name, in Gristmill, for an oil of fine, polished wood ('edel' is German for noble). Beside Gristmill's mahogany, sawdust and walnut, it reads as oiled, varnished woodwork: smooth, warm and a little nutty.",
  src=["pw_gristmill", "fr_gristmill"]),
 "note-guaiac-wood": dict(
  say="The wood of a South American tree, distilled into a thick oil: smoky and woody, like a campfire or incense, but mellow, round and sweet, with balsamic, rosy, vanilla and tobacco facets and a tarry, leathery edge. There is nothing light about it; it gives a perfume dark, smooth depth.",
  src=["fr_guaiac", "ps_guaiac", "fw_guaiac"],
  vars={"Guaiac": dict(same="No change: guaiac is short for guaiac wood.")}),
 "note-mahogany": dict(
  say="The rich, red furniture wood. As a note it is velvety and refined, deep and woody with a faint smokiness and a touch of caramel, like freshly sanded fine wood. It is rare in perfumery and usually built by the perfumer.",
  src=["fr_mahogany", "oz_mahogany", "pw_gristmill"]),
 "note-moldy-cedarwood": dict(
  say="Cedar gone damp and mildewed: the dry, clean pencil wood turned musty, earthy and a little mushroomy, like an old chest in a wet cellar or a coffin in the ground. It is Tombstone's picture of decay.",
  src=["tb_coffin", "ps_cedar"]),
 "note-oak": dict(
  say="The great hardwood of forests and barrels: dry, woody and grounding, a little sharp and sour, with a soft hint of vanilla and dried fruit from its aged wood. Aged in oak, spirits take on its smell, and in a perfume it can read as whisky and barrels.",
  src=["fr_oak", "ps_oak", "oz_oak"],
  vars={"Oakwood": dict(same="No change: oak and oakwood mean the same note.")}),
 "note-oud": dict(
  say="Agarwood: the dark, resin-soaked heartwood of the aquilaria tree of South and Southeast Asia, formed only when the tree is infected and defends itself. It is one of the costliest materials on earth, and one of the strangest: deep, woody and smoky, sweet and balsamic, and often intensely animal, even barnyard, with fruity, leathery and medicinal sides. Where it grows changes it greatly.",
  src=["wp_agarwood", "pf_agarwood", "fr_agarwood", "fr_oudterroir"],
  vars={
   "Agarwood (Oud)": dict(same="No change: agarwood and oud are the same material."),
   "Assam Oud": dict(say="Oud from Assam, in India: the classic, animal oud, deep and intense, earthy, leathery and smoky, with the barnyard funk it is famous for.", src=OUD_ORIGIN + ["fr_ancientoud"]),
   "Cambodian Oud": dict(say="Oud from Cambodia: sweeter and fruitier than Indian oud, with notes of berry jam, honey, dried fruit and resin over the wood, less animal.", src=["fr_cambodianoud"] + OUD_ORIGIN),
   "Laotian Oud": dict(say="Oud from Laos: rugged wood and zesty herbs, sometimes close to Cambodian or Thai oud in its opening.", src=OUD_ORIGIN + ["fr_ancientoud"]),
   "Malaysian Oud": dict(say="Oud from Malaysia: sweeter, more floral and fruity than Indian oud, green and 'jungle'-like, sometimes peppery.", src=OUD_ORIGIN + ["fr_ancientoud"]),
   "Thailand Oud": dict(say="Oud from Thailand, often from the same tree as Cambodian: woody, balsamic, leathery and smoky, with warm animal accents and sometimes fruity or incense-like sides.", src=OUD_ORIGIN + ["fr_ancientoud"]),
   "Vietnamese Oud": dict(say="Oud from Vietnam, known for sharp camphor-like blasts over the wood, with a sweet, resinous depth.", src=OUD_ORIGIN + ["pw_list"]),
   "Clean Bright Oud": dict(say="ADAR's description of an oud without the barnyard: its clean, woody, resinous side, lighter and brighter than the animal ouds of India.", src=["adar_lignum", "fr_agarwood"]),
   "Smoky Oud": dict(say="Oud with its smoky side put forward: burning wood and incense over the resinous agarwood.", src=["adar_odds", "fr_agarwood"]),
   "Rotting Wood (Oud)": dict(say="Pineward naming oud by where it comes from: agarwood forms when the tree is infected by a mould and the wood rots and fills with resin, so its smell holds something of damp, decaying wood.", src=["pw_list", "wp_agarwood"]),
  }),
 "note-patchouli": dict(
  say="The leaves of a bushy mint-family plant from Southeast Asia, dried and distilled. Patchouli is earthy and woody, dark and damp like a forest floor, sweet and balsamic, a little camphorous and chocolatey, and very long-lasting. It carried the hippie perfumes of the 1960s and is the backbone of chypres and many modern perfumes.",
  src=["ps_patch", "fr_patch", "wp_patch"],
  vars={
   "Patchouli (Aceh)": dict(say="Patchouli from Aceh, in northern Sumatra: Indonesia grows nearly all the world's patchouli, and Aceh's is the classic, full, earthy-sweet oil.", src=["fw_patchlight", "wp_patch", "la_walk"]),
   "Patchouli Aceh": dict(say="Patchouli from Aceh, in northern Sumatra, where the classic oil comes from: full, earthy and sweet.", src=["fw_patchlight", "wp_patch", "la_douleur"]),
   "Dark Patchouli": dict(say="The dark oil distilled in iron stills, deep gold to brown: richer, earthier and smokier than light, refined patchouli, with a more complex, lasting dry-down.", src=["fw_patchdark", "fw_patchlight"]),
  }),
 "note-petrified-driftwood": dict(
  say="Wood washed by the sea until it is bleached and hard as stone: a dry, woody note with a salty, mineral, seaside edge, the smell of a beach where the wind carries salt, with none of the tropics in it.",
  src=["ps_driftwood", "fr_driftwood", "adar_incantu"]),
 "note-pineboard": dict(
  say="Freshly cut pine boards: the strong smell of sawn pine, sticky with resin, a little like turpentine, sweet and sharp, the smell of a timber yard.",
  src=["pw_list", "ukw_pine", "fww_resin"]),
 "note-sandalwood": dict(
  say="The heartwood of a slow-growing tree, sacred in India. Its oil is creamy, milky and soft, sweet and warm, rich and smooth, the smoothest wood there is. The famous sandalwood of Mysore has been nearly exhausted, so most sandalwood today is Australian or built from synthetics.",
  src=["fr_sandal", "wp_sandaloil", "pf_indiansandal"],
  vars={
   "Mysore Sandalwood": dict(say="Indian sandalwood from Mysore, Santalum album: the legendary one, the creamiest, milkiest and richest, now almost gone from perfumery because the trees ran out.", src=["wp_santalum", "fr_sandal", "pf_indiansandal"]),
   "Australian Sandalwood": dict(say="A different species, Santalum spicatum: rawer, earthier and sharper than Indian sandalwood, with less of its creamy softness.", src=["wp_sandaloil", "tg_ausandal", "pf_indiansandal"]),
  }),
 "note-sawdust": dict(
  say="The fine dust of a sawmill: soft, creamy and nutty wood, a little powdery and green, like freshly cut timber and pencil shavings.",
  src=["fr_sawdust", "tg_sawdust", "fr_gristmill"]),
 "note-teak-wood": dict(
  say="The dense tropical wood of boat decks and garden furniture. As a note it is a 'blond' woody fantasy, warm and a little smoky, with an old-leather side from the wood's resin. It is built by the perfumer.",
  src=["fr_teak", "oz_teak"]),
 "note-vetiver": dict(
  say="The long, tangled roots of an Indian grass, distilled into one of perfumery's great materials: earthy and woody, smoky and a little green, like damp soil and roots, cool and deep. Where it grows changes it: Haiti's is clean and bright, Java's smoky, Réunion's smooth and sweet.",
  src=["fr_vetiver", "fr_vetivernews", "fw_vethaiti"],
  vars={
   "Absolute Vetiver": dict(say="Vetiver as an absolute, extracted with solvents rather than distilled: thicker and denser, with more of the dark, earthy root.", src=["wp_absolute", "adar_aeth"]),
   "Bourbon Vetiver": dict(say="Vetiver from Réunion (once Île Bourbon): smoother and sweeter, with a rosy note, once the finest and now rare.", src=["fr_vetivernews", "pw_list"]),
   "Haitian Vetiver": dict(say="Vetiver from Haiti, where about nine tenths of the world's vetiver oil comes from: the cleanest and brightest, green, sweetish and even a little floral.", src=["fr_vetivernews", "fw_vethaiti", "st_vethaiti"]),
   "Vetiver (Haiti)": dict(say="Vetiver from Haiti, the largest source: clean, bright and green, sweeter and lighter than the smoky vetiver of Java.", src=["fr_vetivernews", "fw_vethaiti", "la_walk"]),
  }),
 "note-willow-bark": dict(
  say="The bark of the riverbank willow, which holds salicin, the forerunner of aspirin. It smells like peeling a twig by the water: wet wood and cool green sap, a little bitter, with a sharp, medicinal, almost wintergreen edge.",
  src=["cameo_willow", "pp_willow", "tb_coffin"]),
 "note-woody-notes": dict(
  say="No single wood: the whole family of them, from cedar and sandalwood to vetiver, patchouli and oud. Woods can be dry and pencil-like, creamy and soft, or smoky and tarry; they form the base of most perfumes and hold everything above them.",
  src=["fr_woody", "ps_woody"],
  vars={
   "Dry Wood": dict(say="Wood at its driest: dusty, papery and a little smoky, like sun-dried timber in a desert, with none of the creaminess of sandalwood.", src=["fr_drywood", "fr_deserthope"]),
  }),
}
out("WOO", S, N)
